# Generated by Django 4.1.7 on 2023-02-23 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
